#!/bin/bash

base_path=$(pwd);

# Javascript - lmd (lazy module declaration)
hash lmd 2>/dev/null || { 
  echo >&2 -e "\n\tlmd not installed. $(tput setaf 2)npm install lmd -g$(tput sgr0) or $(tput setaf 7)github.com/azproduction/lmd$(tput sgr0)\n";
  exit 1;
}

# SCSS - compass
hash compass 2>/dev/null || { 
  echo >&2 -e "\n\tcompass not installed. $(tput setaf 2)gem install compass$(tput sgr0) or $(tput setaf 7)compass-style.org/install$(tput sgr0)\n";
  exit 1;
}

cd $base_path"/src/etherous/static/assets/js/" && lmd watch config/development.lmd.json application.dev.js&

cd $base_path"/src/etherous/static/assets/scss/" && compass watch&
