application: etherous-app
version: 0-african-wild-ass
runtime: python27
api_version: 1
threadsafe: true

default_expiration: '5d'

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /assets
  static_dir: etherous/static/assets

- url: /favicon.ico
  static_files: etherous/static/assets/img/icons/favicon.ico
  upload: etherous/static/assets/img/icons/favicon.ico

- url: /crossdomain.xml
  static_files: etherous/static/crossdomain.xml
  upload: etherous/static/crossdomain.xml

- url: /humans.txt
  static_files: etherous/static/humans.txt
  upload: etherous/static/humans.txt

- url: /robots.txt
  static_files: etherous/static/robots.txt
  upload: etherous/static/robots.txt

- url: .*
  script: engine.app
  secure: always
